server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Без кэша для HTML и JS — чтобы изменения сразу видны
    location ~* \.(html|js)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        expires 0;
    }

    # CSS можно кэшировать
    location ~* \.css$ {
        expires 1d;
        add_header Cache-Control "public";
    }
}
